### PR TITLE
version 0.1.3

### LINKED ISSUE #29: push new version
Hi, I stumbled onto the issue of `Compat` restricting the version of `DataFrames`, which was fixed in #28.

Could a new version of this package be pushed?

### PR DESCRIPTION
**Pull request by haakon-e**
resolves #29.

integrates a few useful commits from ~1 year ago.

### CODE REVIEW

**Comment by truedichotomy** [comment]
Any update on getting a new version of NCDatasets released?

**Comment by haakon-e** [comment]
> Any update on getting a new version of NCDatasets released?

I don't have commit access to this repo. Perhaps @Alexander-Barth or @kouketsu could get the ball rolling?

**Comment by Alexander-Barth** [comment]
ok, I am trying to make a new release. I am surprised that the [release v0.1.2](https://github.com/JuliaRegistries/General/blob/d42f29986ba0db622fe5b87a63185a85d56bbcad/G/GibbsSeaWater/Versions.toml#L7) does not show up on github. I just updated the TabBot.yml workflow.

**Comment by Alexander-Barth** [comment]
see https://github.com/TEOS-10/GibbsSeaWater.jl/issues/31

**Pull request merged**
